### ISSUE TITLE
请教一下BCM4709 Cortex A9应该选哪一个文件啊

### ISSUE THREAD

**Issue by m1omoe** [gaoyb7/115drive-webdav#10]
试了V7的报错了![](https://s3.bmp.ovh/imgs/2022/08/11/85554e1ac4d107bc.png)

**Comment by gaoyb7** [comment]
> 试了V7的报错了![](https://camo.githubusercontent.com/2d1d7b4f6a42ddd534891804e89bfbfa116239d4a0f54c38f2df62dbd4632df8/68747470733a2f2f73332e626d702e6f76682f696d67732f323032322f30382f31312f383535353465316163346431303762632e706e67)

试下 v6、v5 的？这个有点旧了。

**Comment by m1omoe** [comment]
> > 试了V7的报错了![](https://camo.githubusercontent.com/2d1d7b4f6a42ddd534891804e89bfbfa116239d4a0f54c38f2df62dbd4632df8/68747470733a2f2f73332e626d702e6f76682f696d67732f323032322f30382f31312f383535353465316163346431303762632e706e67)
> 
> 试下 v6、v5 的？这个有点旧了。

试了下V6的可以了感谢
