### ISSUE TITLE
求个梅林版本的webdav

### ISSUE THREAD

**Issue by luffycc** [gaoyb7/115drive-webdav#11]
求个梅林版本的webdav

**Comment by gaoyb7** [comment]
> 求个梅林版本的webdav

没设备测试，直接下对应的二进制包跑看看？

**Comment by stebrick** [comment]
> > 求个梅林版本的webdav
> 
> 没设备测试，直接下对应的二进制包跑看看？

同求，下了好幾個包都安裝不了，我的是Asus XT8 (cpu armv7)，刷了KoolCenter固件386.5_2
報錯如下圖，應該要另外有一個編譯包讓梅林固件跑才可以。

另外，如需參考可以到AliyunWebDav裡的源碼看看，他們有編譯包是讓梅林固件跑的，有了編譯包我們可以幫你測試﹕https://github.com/messense/aliyundrive-webdav/releases

![chrome_oy8MK7L2MQ](https://user-images.githubusercontent.com/17674465/186340554-016c48dd-e629-4326-9338-434cc4c87a7a.png)

**Comment by gaoyb7** [comment]
> > > 求个梅林版本的webdav
> > 
> > 
> > 没设备测试，直接下对应的二进制包跑看看？
> 
> 同求，下了好幾個包都安裝不了，我的是Asus XT8 (cpu armv7)，刷了KoolCenter固件386.5_2 報錯如下圖，應該要另外有一個編譯包讓梅林固件跑才可以。
> 
> 另外，如需參考可以到AliyunWebDav裡的源碼看看，他們有編譯包是讓梅林固件跑的，有了編譯包我們可以幫你測試﹕https://github.com/messense/aliyundrive-webdav/releases
> 
> ![chrome_oy8MK7L2MQ](https://user-images.githubusercontent.com/17674465/186340554-016c48dd-e629-4326-9338-434cc4c87a7a.png)

这不是梅林安装包，不能上传直接安装的，需要ssh连上去手动下载解压
