### ISSUE TITLE
关于下载速度的问题

### ISSUE THREAD

**Issue by q4232134** [gaoyb7/115drive-webdav#12]
我用手机版或者网页版115下载文件大概是30MBps,但是用webdav下载，无论是多少个文件，总速度只有1.5MBps左右，请问限制在接口还是我使用的uid还是其他哪些地方？

**Comment by q4232134** [comment]
找到原因了，是因为下载地址流量走了域名代理，换成内网地址就可以了

**Comment by oushu1yexinhao1** [comment]
> 找到原因了，是因为下载地址流量走了域名代理，换成内网地址就可以了

老哥，具体咋整呢，我这代理也没跑这个下载请求啊，也是只有500kb，直接115客户端下载有40MB/s

**Comment by oushu1yexinhao1** [comment]
> 

我群晖挂载的webDav速度正常，就是WebDAVFS的速度不正常
