### ISSUE TITLE
发现服务经常日志有401错误

### ISSUE THREAD

**Issue by sleikang** [gaoyb7/115drive-webdav#15]
![image](https://user-images.githubusercontent.com/23020770/184757614-f9841b8e-d3a0-4ff2-b800-e661d322f6b2.png)
测试是发现只有winscp链接的时候才不会报错，用clouddrive和alist这2个工具去链接都会报错，好像是这2个客户端请求头少了下面这个的原因，能否关闭这个验证，我看了下代码不知道哪里设置
Authorization: Basic dXNlcjoxMjM0NTY=

**Comment by sleikang** [comment]
找到了 已经自己关闭了
![image](https://user-images.githubusercontent.com/23020770/184758300-ad4ebca4-d8b0-439f-aaab-81205bfd6d9a.png)

**Comment by gaoyb7** [comment]
> 找到了 已经自己关闭了
> ![image](https://user-images.githubusercontent.com/23020770/184758300-ad4ebca4-d8b0-439f-aaab-81205bfd6d9a.png)



> ![image](https://user-images.githubusercontent.com/23020770/184757614-f9841b8e-d3a0-4ff2-b800-e661d322f6b2.png)
> 测试是发现只有winscp链接的时候才不会报错，用clouddrive和alist这2个工具去链接都会报错，好像是这2个客户端请求头少了下面这个的原因，能否关闭这个验证，我看了下代码不知道哪里设置
> Authorization: Basic dXNlcjoxMjM0NTY=

密码鉴权这是正常的，很多客户端会先尝试无密码访问，失败了再用密码访问，忽略就行
