### ISSUE TITLE
新建目录后加载目录树有BUG

### ISSUE THREAD

**Issue by sleikang** [gaoyb7/115drive-webdav#16]
如图所示，但是不是每次都会出现，115服务器内部其实是没有这个目录的
![image](https://user-images.githubusercontent.com/23020770/184763317-a54b93ad-83fe-4f2f-9210-1e1aeed315a2.png)

**Comment by sleikang** [comment]
有时候还会出现我从115客户端删除了目录，然后这个目录还存在
![image](https://user-images.githubusercontent.com/23020770/184766898-e53eb303-fba7-46c1-a3d5-5d3b7cfd3868.png)

**Comment by gaoyb7** [comment]
你这用的是 Clouddrive？

**Comment by gaoyb7** [comment]
> 如图所示，但是不是每次都会出现，115服务器内部其实是没有这个目录的
> ![image](https://user-images.githubusercontent.com/23020770/184763317-a54b93ad-83fe-4f2f-9210-1e1aeed315a2.png)

你这用的是CloudDrive ？

**Comment by gaoyb7** [comment]
> 有时候还会出现我从115客户端删除了目录，然后这个目录还存在
> ![image](https://user-images.githubusercontent.com/23020770/184766898-e53eb303-fba7-46c1-a3d5-5d3b7cfd3868.png)

webdav 加了目录缓存的，2分钟。你用 115app 新建目录webdav不知道，所以缓存没刷新，等2分钟缓存失效了重新加载就行。另外看你截图像是在用 clouddrive，不是webdav

**Comment by sleikang** [comment]
> > 如图所示，但是不是每次都会出现，115服务器内部其实是没有这个目录的
> > ![图像](https://user-images.githubusercontent.com/23020770/184763317-a54b93ad-83fe-4f2f-9210-1e1aeed315a2.png)
> 
> 你这用的是CloudDrive ？

对我用clouddrive挂载webdav，然后在本地磁盘新建目录

**Comment by sleikang** [comment]
> > 有时候还会出现我从115客户端删除了目录，然后这个目录还存在
> > ![图像](https://user-images.githubusercontent.com/23020770/184766898-e53eb303-fba7-46c1-a3d5-5d3b7cfd3868.png)
> 
> webdav 加了目录缓存的，2分钟。你用 115app 新建目录webdav不知道，所以缓存没刷新，等2分钟缓存失效了重新加载就行。另外看你截图像是在用 clouddrive，不是webdav

哦哦哦，这个是从115客户端删除了这个目录，然本地目录没更新，这个就不影响了，那就是有一个问题就是在本地磁盘新建目录的时候，新建目录的里面有个多余的重复文件夹名称，其实这个不存在

**Comment by gaoyb7** [comment]
> > > 有时候还会出现我从115客户端删除了目录，然后这个目录还存在
> > > ![图像](https://user-images.githubusercontent.com/23020770/184766898-e53eb303-fba7-46c1-a3d5-5d3b7cfd3868.png)
> > 
> > 
> > webdav 加了目录缓存的，2分钟。你用 115app 新建目录webdav不知道，所以缓存没刷新，等2分钟缓存失效了重新加载就行。另外看你截图像是在用 clouddrive，不是webdav
> 
> 哦哦哦，这个是从115客户端删除了这个目录，然本地目录没更新，这个就不影响了，那就是有一个问题就是在本地磁盘新建目录的时候，新建目录的里面有个多余的重复文件夹名称，其实这个不存在

你看下日志，有没有新建内层目录的请求，没有的话可能就是 clouddrive 自身的问题

**Comment by sleikang** [comment]
> > > > 有时候还会出现我从115客户端删除了目录，然后这个目录还存在
> > > > ![图像](https://user-images.githubusercontent.com/23020770/184766898-e53eb303-fba7-46c1-a3d5-5d3b7cfd3868.png)
> > > 
> > > 
> > > webdav 加了目录缓存的，2分钟。你用 115app 新建目录webdav不知道，所以缓存没刷新，等2分钟缓存失效了重新加载就行。另外看你截图像是在用 clouddrive，不是webdav
> > 
> > 
> > 哦哦哦，这个是从115客户端删除了这个目录，然本地目录没更新，这个就不影响了，那就是有一个问题就是在本地磁盘新建目录的时候，新建目录的里面有个多余的重复文件夹名称，其实这个不存在
> 
> 你看下日志，有没有新建内层目录的请求，没有的话可能就是 clouddrive 自身的问题

嗯 确实是clouddrive的问题，我挂载到alist测试新建目录不会出现这种问题
