### ISSUE TITLE
Docker挂载后无法复制文件 都是403错误

### ISSUE THREAD

**Issue by yuefengkai** [gaoyb7/115drive-webdav#19]
<img width="404" alt="image" src="https://user-images.githubusercontent.com/2100585/185772160-58c46add-4f91-4fdc-a700-71dea9a6fcdd.png">
<img width="627" alt="image" src="https://user-images.githubusercontent.com/2100585/185772168-f656c57a-b456-4d52-856c-0397a9d4808e.png">

**Comment by gaoyb7** [comment]
你是在扫库么，操作太频繁了，触发115限流了

**Comment by gaoyb7** [comment]
> <img alt="image" width="404" src="https://user-images.githubusercontent.com/2100585/185772160-58c46add-4f91-4fdc-a700-71dea9a6fcdd.png">
> 
> <img alt="image" width="627" src="https://user-images.githubusercontent.com/2100585/185772168-f656c57a-b456-4d52-856c-0397a9d4808e.png">

你操作太频繁了，触发 115限流

**Comment by yuefengkai** [comment]
也没有吧！我就尝试打开文件夹然后复制出来。 不过文件夹文件比较多---- 回复的原邮件 ***@***.***>发送日期2022年08月21日 11:21 ***@***.***> 抄送人Zengzhi ***@***.******@***.***>主题Re: [gaoyb7/115drive-webdav] Docker挂载后无法复制文件 都是403错误 (Issue #19)









你操作太频繁了，触发 115限流



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/gaoyb7/115drive-webdav/issues/19#issuecomment-1221459119",

"url": "https://github.com/gaoyb7/115drive-webdav/issues/19#issuecomment-1221459119",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by gaoyb7** [comment]
> 也没有吧！我就尝试打开文件夹然后复制出来。 不过文件夹文件比较多---- 回复的原邮件 ***@***.***>发送日期2022年08月21日 11:21 ***@***.***> 抄送人Zengzhi ***@***.******@***.***>主题Re: [gaoyb7/115drive-webdav] Docker挂载后无法复制文件 都是403错误 (Issue #19) 你操作太频繁了，触发 115限流 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***> [ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "[#19 (comment)](https://github.com/gaoyb7/115drive-webdav/issues/19#issuecomment-1221459119)", "url": "[#19 (comment)](https://github.com/gaoyb7/115drive-webdav/issues/19#issuecomment-1221459119)", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

文件夹下载。里边文件太多了吧，115最多只能5个文件同时下载，你控制下并发量
