### ISSUE TITLE
115drive-webdav的Windows版一打开就会弹出来，还有Linux版也没法打开

### ISSUE THREAD

**Issue by wh1235** [gaoyb7/115drive-webdav#2]

**Comment by wh1235** [comment]
可以支持Linux和Windows的amd64版就好了

**Comment by gaoyb7** [comment]
> 

[Linux_x86_64.tar.gz](https://github.com/gaoyb7/115drive-webdav/releases/download/v0.1.1/115drive-webdav_0.1.1_Linux_x86_64.tar.gz)

**Comment by gaoyb7** [comment]
> 可以支持Linux和Windows的amd64版就好了

Linux_x86_64、Windows_x86_64 就是 amd64 版了。。要在命令行下跑，你使用姿势的问题

**Comment by sunny32cool** [comment]
有幸看到大佬的工具 不知道这个能否在openwrt x86的软路由上实现115的挂载呢。我是小白，希望大佬百忙中能有机会出个教程！感谢！

**Comment by whws** [comment]
> > 可以支持Linux和Windows的amd64版就好了
> 
> Linux_x86_64、Windows_x86_64 就是 amd64 版了。。要在命令行下跑，你使用姿势的问题

请问一下怎么运行呢？我是小白，可能有许多流程不懂
