### ISSUE TITLE
Docker里配置容器好像通常都是用环境变量来传递参数的？

### ISSUE THREAD

**Issue by nov12** [gaoyb7/115drive-webdav#20]
可否修改下，方便后续的镜像升级和日常维护。

**Comment by gaoyb7** [comment]
> 可否修改下，方便后续的镜像升级和日常维护。

命令行和环境变量没太大区别吧，都是随手改的事情

**Comment by nov12** [comment]
我也不是很精通，但是简而言之……我在群晖里很不方便。群晖里只有新建容器，才能编辑运行参数。如果发生变化只能删除容器重新再建立。其次，群晖里不允许参数里出现等号，我试了几次发现。

而且环境变量在portainer之类的gui配置很方便，一个参数一个输入框，如果是命令行参数，就只能一个文本框输入修改，尤其是seid还那么长……


算了，我现在直接用编译好的程序挂在家里的服务器上了，总之感谢您的程序。很好用。

吐槽：115 啥时候能出一个官方webdav就好了，反正现在离线和下载都封杀的差不多了。真郁闷，另外到现在还不支持音轨选择

**Comment by gaoyb7** [comment]
> 我也不是很精通，但是简而言之……我在群晖里很不方便。群晖里只有新建容器，才能编辑运行参数。如果发生变化只能删除容器重新再建立。其次，群晖里不允许参数里出现等号，我试了几次发现。
> 
> 而且环境变量在portainer之类的gui配置很方便，一个参数一个输入框，如果是命令行参数，就只能一个文本框输入修改，尤其是seid还那么长……
> 
> 算了，我现在直接用编译好的程序挂在家里的服务器上了，总之感谢您的程序。很好用。
> 
> 吐槽：115 啥时候能出一个官方webdav就好了，反正现在离线和下载都封杀的差不多了。真郁闷，另外到现在还不支持音轨选择

可以直接用 --config xxx.json 的方式运行, 参数都写到配置文件里边去, 参考代码仓库里边的配置样例
