### ISSUE TITLE
能否出一个安装在openwrt的教材或者插件包

### ISSUE THREAD

**Issue by Kisoul** [gaoyb7/115drive-webdav#23]
希望大佬能出一个安装在openwrt x86的教程或者像[luci-app-aliyundrive-webdav]插件一样供大家自行编译。万分感谢。

**Comment by gaoyb7** [comment]
> 希望大佬能出一个安装在openwrt x86的教程或者像[luci-app-aliyundrive-webdav]插件一样供大家自行编译。万分感谢。

可以直接用 docker 跑，没有 luci 插件开发的计划

**Comment by Kisoul** [comment]
> > 希望大佬能出一个安装在openwrt x86的教程或者像[luci-app-aliyundrive-webdav]插件一样供大家自行编译。万分感谢。
> 
> 可以直接用 docker 跑，没有 luci 插件开发的计划

感谢大佬及时回复，我还是会定期看看大佬的开发计划。docker教程我去翻翻，谢谢
