### ISSUE TITLE
[Windows 10] - 不明報錯

### ISSUE THREAD

**Issue by stebrick** [gaoyb7/115drive-webdav#25]
登入成功，但用potplayer報出以下錯誤

`time="2022-09-10T21:28:29+08:00" level=error msg="handleGetHeadPost, call h.DriveClient.GetFile fail, req_path: /劇集/02.smi" func="github.com/gaoyb7/115drive-webdav/webdav.(*Handler).handleGetHeadPost" file="/home/runner/work/115drive-webdav/115drive-webdav/webdav/webdav.go:116" error="not found"`

`time="2022-09-10T21:28:29+08:00" level=error msg="err: not found" func=main.startWebdavServer.func1 file="/home/runner/work/115drive-webdav/115drive-webdav/main.go:31" method=GET path="/劇集/02.smi"`

用winscp下載報出以下錯誤﹕

`WebDAV resource moved to 'http://xxx.xx.xx.xxx/cdnfhnfile.115.com/...vip-367XXXXXXX--1&c=2&f=1&k=XXXXXXXXXXXXXXXXus=XXXXX0&uc=10&v=1'.
302 Found
`

應該如何解決？

**Comment by gaoyb7** [comment]
你用的应该是旧的版本升级下吧

**Comment by stebrick** [comment]
> 你用的应该是旧的版本升级下吧

不可能呀，用的是這個 115drive-webdav_0.1.4_Windows_x86_64.tar.gz.
115drive-webdav.exe 修改日期是9/5/2022 6:37PM的。
