### ISSUE TITLE
下载接口应该是更新了，播放都是返回500

### ISSUE THREAD

**Issue by XiaolinLeo** [gaoyb7/115drive-webdav#27]
下载接口应该是更新了，目前挂载到本地，读取文件播放接口都是返回500

**Comment by fanbin8592** [comment]
对，播放不了了。目录是可以读取的。

**Comment by luvjojo** [comment]
今天已经播放不了了，求更新

**Comment by wsjmxz** [comment]
求大佬更新！！！ 115接口昨天变了！

**Comment by gaoyb7** [comment]
修复支持了 Linux x86_64 的版本，其他的暂时无解

**Comment by stb1238921** [comment]
大佬，我是群晖docker，群晖是x86版。更新最新0.1.5版后无法启动，报 
standard_init_linux.go:230: exec user process caused: no such file or directory 错误

**Comment by ivensfor** [comment]
> 大佬，我是群晖docker，群晖是x86版。更新最新0.1.5版后无法启动，报 standard_init_linux.go:230: exec user process caused: no such file or directory 错误

一样的问题，更新后目前无法登录，等大佬更新吧。

**Comment by qq57240** [comment]
> 修复支持了 Linux x86_64 的版本，其他的暂时无解

Linux x86_64 0.15 依然500

**Comment by gaoyb7** [comment]
> > 大佬，我是群晖docker，群晖是x86版。更新最新0.1.5版后无法启动，报 standard_init_linux.go:230: exec user process caused: no such file or directory 错误
> 
> 一样的问题，更新后目前无法登录，等大佬更新吧。

docker 更新到 0.1.6 版本就 ok 了

**Comment by gaoyb7** [comment]
> > 修复支持了 Linux x86_64 的版本，其他的暂时无解
> 
> Linux x86_64 0.15 依然500

需要用 app 的 cookie，不支持浏览器的 cookie

**Comment by youyifentian** [comment]
> > > 修复支持了 Linux x86_64 的版本，其他的暂时无解
> > 
> > 
> > Linux x86_64 0.15 依然500
> 
> 需要用 app 的 cookie，不支持浏览器的 cookie

能不能搞一个扫码登录或者扫码就能获取cookie的东西，app抓包属实有点太难了

**Comment by gaoyb7** [comment]
> > > > 修复支持了 Linux x86_64 的版本，其他的暂时无解
> > > 
> > > 
> > > Linux x86_64 0.15 依然500
> > 
> > 
> > 需要用 app 的 cookie，不支持浏览器的 cookie
> 
> 能不能搞一个扫码登录或者扫码就能获取cookie的东西，app抓包属实有点太难了

没计划 docker 扫码不方便，抓包本来就不是什么困难的事，跟着教程做就好
