### ISSUE TITLE
有幸看到大佬的工具 不知道这个能否在openwrt x86的软路由上实现115的挂载呢。我是小白，希望大佬百忙中能有机会出个教程！感谢！

### ISSUE THREAD

**Issue by sunny32cool** [gaoyb7/115drive-webdav#3]

**Comment by samulo7** [comment]
直接在exe所在路径，敲115-webdav.exe --host=0.0.0.0 --port=8080 --user=user --pwd=123456 --uid=xxxxxx --cid=xxxxxxx --seid=xxxxx
