### ISSUE TITLE
希望可以设置115单线程缓存大小

### ISSUE THREAD

**Issue by youshandefeiyang** [gaoyb7/115drive-webdav#32]
Clouddrive有一个功能，叫Cloud115ThreadReadLengthInKB，可以自定义单线程缓存的内容大小，虽然不利于频繁的快进快退，但是利于极限速度的发挥，现在115用阿里云后单线程确实快了不少，已经能达到二三百Mbps了，这个速度已经可以看4K原盘了，我看代码UA已经是115Browser了，希望本项目和rclone-mod可以加入此功能，通过传参用户自定义指定缓存大小

**Comment by youshandefeiyang** [comment]
clouddrive开发者曾经提出的一个方案，在下载一个文件时候，同时上传一个相同SHA1的临时文件，然后实现倍速叠加下载该文件，巧妙的利用了115多线程的速度。

**Comment by gaoyb7** [comment]
> clouddrive开发者曾经提出的一个方案，在下载一个文件时候，同时上传一个相同SHA1的临时文件，然后实现倍速叠加下载该文件，巧妙的利用了115多线程的速度。

现在 115 单线程下载 15M，对应的就是 120Mbps 视频的码率，基本不存在播放不了的视频。另外 rclone 本身就支持缓存，buffer-size、vfs 等配置。

**Comment by gaoyb7** [comment]
> Clouddrive有一个功能，叫Cloud115ThreadReadLengthInKB，可以自定义单线程缓存的内容大小，虽然不利于频繁的快进快退，但是利于极限速度的发挥，现在115用阿里云后单线程确实快了不少，已经能达到二三百Mbps了，这个速度已经可以看4K原盘了，我看代码UA已经是115Browser了，希望本项目和rclone-mod可以加入此功能，通过传参用户自定义指定缓存大小

https://rclone.org/commands/rclone_serve_webdav/#vfs-chunked-reading
https://rclone.org/commands/rclone_mount/#vfs-chunked-reading
https://rclone.org/docs/#buffer-size-size

**Comment by youshandefeiyang** [comment]
好的，我再仔细看看
