### ISSUE TITLE
GetFileURL已经变更且无法使用了

### ISSUE THREAD

**Issue by SheltonZhu** [gaoyb7/115drive-webdav#34]
如题

**Comment by gaoyb7** [comment]
> 如题

可以使用，我这边正常

**Comment by SheltonZhu** [comment]
用docker运行了是可以的，但是我用单元测试跑响应体为空，我在看下，打扰大佬了。。

**Comment by SheltonZhu** [comment]
本地从源码跑就403.
![image](https://user-images.githubusercontent.com/26734784/197537520-fbaf6d56-ca74-47fc-a23f-f760be31d7b9.png)
通过docker的镜像能成功触发206
![image](https://user-images.githubusercontent.com/26734784/197537776-c1ec29eb-fc0c-4ba5-8214-6fa6d3b27c66.png)
这是为啥呢
