### ISSUE TITLE
报错，文件夹目录中含有特殊符号如  /  就打不开目录了 会报错，nplayer和fileball都是这样

### ISSUE THREAD

**Issue by isChengshi** [gaoyb7/115drive-webdav#35]
报错，文件夹目录中含有特殊符号如  /  就打不开目录了 会报错，nplayer和fileball都是这样

感谢制作115drive，好用！

**Comment by isChengshi** [comment]
大佬看到这条报错了吗？  目前仅发现目录里带  /  的存在这种问题

**Comment by gaoyb7** [comment]
> 大佬看到这条报错了吗？ 目前仅发现目录里带 / 的存在这种问题

非法字符。本身 115 app 建这种目录也会报错

**Comment by isChengshi** [comment]
> 

网页端建立的文件夹带/，APP也是可以访问的啊

**Comment by anyingxiuluo** [comment]
大佬，用这个webdabv挂载115，单线程下载速度1m/s左右，这是115官方的限制吗
