### ISSUE TITLE
可否增加类似Alist的文件下载请求不走服务器？NAS的上传小水管太限制外网使用了

### ISSUE THREAD

**Issue by isChengshi** [gaoyb7/115drive-webdav#36]
![image](https://user-images.githubusercontent.com/102446831/197706778-5233c415-9e82-4187-857f-eba3d0ee34a7.png)

**Comment by gaoyb7** [comment]
> ![image](https://user-images.githubusercontent.com/102446831/197706778-5233c415-9e82-4187-857f-eba3d0ee34a7.png)

115 的文件下载地址需要 cookie 校验，所以只能中转
