### ISSUE TITLE
为什么不支持文件上传呢？

### ISSUE THREAD

**Issue by rijcm** [gaoyb7/115drive-webdav#37]
有没有可能实现文件上传呢？主要是哪里被限制了，这个功能还是挺实用的。

**Comment by gaoyb7** [comment]
> 有没有可能实现文件上传呢？主要是哪里被限制了，这个功能还是挺实用的。

1. webdav 上传和秒传不兼容
2. 上传大小限制 5G
3. 115 大部分都是离线下载使用比较多

综上功能鸡肋没什么必要。

**Comment by Jieoz** [comment]
如果配合上[这个](https://imnks.com/6088.html)用群晖的Cloudsync同步就太完美了
