### ISSUE TITLE
请问如果UID、CID、SEID失效怎么更换？

### ISSUE THREAD

**Issue by cdj8105** [gaoyb7/115drive-webdav#38]
用的N1的openwrt，docker安装的115drive-webdav，芝杜播放器连接看视频的。安装方式是“# 通过命令参数获取配置”已成功，请问如果UID、CID、SEID失效怎么更换？还是“# 通过命令参数获取配置”那些命令再拉一次吗？

**Comment by gaoyb7** [comment]
> 用的N1的openwrt，docker安装的115drive-webdav，芝杜播放器连接看视频的。安装方式是“# 通过命令参数获取配置”已成功，请问如果UID、CID、SEID失效怎么更换？还是“# 通过命令参数获取配置”那些命令再拉一次吗？

更换命令。或者通过配置文件的方式启动服务，失效修改配置文件重启
