### ISSUE TITLE
> 用的N1的openwrt，docker安装的115drive-webdav，芝杜播放器连接看视频的。安装方式是“# 通过命令参数获取配置”已成功，请问如果UID、CID、SEID失效怎么更换？还是“# 通过命令参数获取配置”那些命令再拉一次吗？

### ISSUE THREAD

**Issue by cdj8105** [gaoyb7/115drive-webdav#39]
> 用的N1的openwrt，docker安装的115drive-webdav，芝杜播放器连接看视频的。安装方式是“# 通过命令参数获取配置”已成功，请问如果UID、CID、SEID失效怎么更换？还是“# 通过命令参数获取配置”那些命令再拉一次吗？

更换命令。或者通过配置文件的方式启动服务，失效修改配置文件重启

_Originally posted by @gaoyb7 in https://github.com/gaoyb7/115drive-webdav/issues/38#issuecomment-1298131602_
      谢谢大佬回复，能给出具体的命令吗？这个看115视频很好用的

**Comment by gaoyb7** [comment]
> ```
>     > 用的N1的openwrt，docker安装的115drive-webdav，芝杜播放器连接看视频的。安装方式是“# 通过命令参数获取配置”已成功，请问如果UID、CID、SEID失效怎么更换？还是“# 通过命令参数获取配置”那些命令再拉一次吗？
> ```
> 
> 更换命令。或者通过配置文件的方式启动服务，失效修改配置文件重启
> 
> _Originally posted by @gaoyb7 in [#38 (comment)](https://github.com/gaoyb7/115drive-webdav/issues/38#issuecomment-1298131602)_ 谢谢大佬回复，能给出具体的命令吗？这个看115视频很好用的

首页已经有说明了
