### ISSUE TITLE
是否支持离线下载呢?

### ISSUE THREAD

**Issue by snowman** [gaoyb7/115drive-webdav#42]

**Comment by snowman** [comment]
see https://github.com/coolzilj/lixian-115 and https://github.com/deadblue/elevengo

**Comment by gaoyb7** [comment]
> 

离线下载和 webdav 服务是两码事。

**Comment by gaoyb7** [comment]
> see https://github.com/coolzilj/lixian-115 and https://github.com/deadblue/elevengo

离线下载和 webdav 服务是两码事。
