### ISSUE TITLE
网速问题

### ISSUE THREAD

**Issue by youmikuang** [gaoyb7/115drive-webdav#49]
我这限速，打开任何视频都不会超过 8m/s 。不是我一个人的问题吧？

**Comment by Kaystar** [comment]
你这算好的了，我用的rclone改晚上只有三四M的速度。不知道是不是移动端cookie的问题。虽然最近115在晚上开始限速了，应该也有10M的

**Comment by youmikuang** [comment]
> 你这算好的了，我用的rclone改晚上只有三四M的速度。不知道是不是移动端cookie的问题。虽然最近115在晚上开始限速了，应该也有10M的

我一般都是 5m/s 内

**Comment by Kaystar** [comment]
> > 你这算好的了，我用的rclone改晚上只有三四M的速度。不知道是不是移动端cookie的问题。虽然最近115在晚上开始限速了，应该也有10M的
> 
> 我一般都是 5m/s 内

那差不多，我用另外一个挂载软件使用的是Linux端扫码登录的，速度是10M左右。所以我觉得应该就是移动端cookie的原因了，被115限制的更厉害一点

**Comment by youmikuang** [comment]
> > > 你这算好的了，我用的rclone改晚上只有三四M的速度。不知道是不是移动端cookie的问题。虽然最近115在晚上开始限速了，应该也有10M的
> > 
> > 
> > 我一般都是 5m/s 内
> 
> 那差不多，我用另外一个挂载软件使用的是Linux端扫码登录的，速度是10M左右。所以我觉得应该就是移动端cookie的原因了，被115限制的更厉害一点

哎，不支持退款，速度上 115 还不如阿里呢

**Comment by Kaystar** [comment]
> > > > 你这算好的了，我用的rclone改晚上只有三四M的速度。不知道是不是移动端cookie的问题。虽然最近115在晚上开始限速了，应该也有10M的
> > > 
> > > 
> > > 我一般都是 5m/s 内
> > 
> > 
> > 那差不多，我用另外一个挂载软件使用的是Linux端扫码登录的，速度是10M左右。所以我觉得应该就是移动端cookie的原因了，被115限制的更厉害一点
> 
> 哎，不支持退款，速度上 115 还不如阿里呢

我说的也不一定对，看大佬怎么说吧

**Comment by kakaloe-ui** [comment]
用临时cdn速度很快，但是tm 最近cdn功能不能用了。
不知道有没有人遇到过，
https://github.com/ChenyangGao/p115client/issues/21
