### ISSUE TITLE
Method Not Allowed

### ISSUE THREAD

**Issue by zhexinlv** [gaoyb7/115drive-webdav#8]
尊敬的先生/女士：
　　
　　您好，感谢你提供的这个开源项目，我计划使用115网盘的Webdav，但按照您的read.me操作（配置个人的相关信息）还是出现了问题。因此，想向您咨询一下，我存在的问题。

系统：
MacOS Catalina Version 10.15.7

处理器：

2.5 GHz Dual-Core Intel Core i5

下载包：
115drive-webdav_0.1.3_Darwin_x86_64.tar.gz 

![image](https://user-images.githubusercontent.com/26533582/183863757-eaf6e8bb-6395-4bc2-afdf-b2b7dfae8d66.png)

在浏览器出现：Method Not allowed

![image](https://user-images.githubusercontent.com/26533582/183864014-7cd83a46-40bf-4827-80b9-38d5f9a37b84.png)

请问：是我host和port的设置出现问题了么？ 还是说需要其它的包支持？

谢谢，

　　祝您一切顺利！

**Comment by gaoyb7** [comment]
要用支持 WebDav 协议的客户端去连，浏览器直连暂时不支持，osx 可以用自带的 访达 去连，不过不太好用， 可以参考 https://support.apple.com/zh-cn/guide/mac-help/mchlp1546/mac

**Comment by zhexinlv** [comment]
> 要用支持 WebDav 协议的客户端去连，浏览器直连暂时不支持，osx 可以用自带的 访达 去连，不过不太好用， 可以参考 https://support.apple.com/zh-cn/guide/mac-help/mchlp1546/mac

谢谢您，按您提供的链接操作，已经成功连接了，开心。

![image](https://user-images.githubusercontent.com/26533582/183884680-090f3d59-8333-4286-86f1-3ab432c09e6e.png)


![image](https://user-images.githubusercontent.com/26533582/183885060-a27cf8ed-09d8-4cc4-8010-5c6dcfa409e9.png)


![image](https://user-images.githubusercontent.com/26533582/183882598-26ded880-9990-4a01-aba4-621ec5bfe967.png)

其实，我看到您的这个项目是想用115网盘的WebDav服务来管理文献的，zotero　(会存在pdf等文件的上传下载);

我看到您项目下面提到的功能，是不存在文件的上传的，就是说目前我还是不能采用这个方案解决我文献管理的问题是吧？

**Comment by gaoyb7** [comment]
是的，暂时不支持文件上传，一般用这个网盘的大部分都是离线下载资源，上传的需求比较少

**Comment by gaoyb7** [comment]
> > 要用支持 WebDav 协议的客户端去连，浏览器直连暂时不支持，osx 可以用自带的 访达 去连，不过不太好用， 可以参考 https://support.apple.com/zh-cn/guide/mac-help/mchlp1546/mac
> 
> 谢谢您，按您提供的链接操作，已经成功连接了，开心。
> 
> ![image](https://user-images.githubusercontent.com/26533582/183884680-090f3d59-8333-4286-86f1-3ab432c09e6e.png)
> 
> ![image](https://user-images.githubusercontent.com/26533582/183885060-a27cf8ed-09d8-4cc4-8010-5c6dcfa409e9.png)
> 
> ![image](https://user-images.githubusercontent.com/26533582/183882598-26ded880-9990-4a01-aba4-621ec5bfe967.png)
> 
> 其实，我看到您的这个项目是想用115网盘的WebDav服务来管理文献的，zotero　(会存在pdf等文件的上传下载);
> 
> 我看到您项目下面提到的功能，是不存在文件的上传的，就是说目前我还是不能采用这个方案解决我文献管理的问题是吧？


是的，暂时不支持文件上传，一般用这个网盘的大部分都是离线下载资源，上传的需求比较少

**Comment by zhexinlv** [comment]
> 

好的，太感谢您了，我大概明白了。
