### ISSUE TITLE
支持账号密码登录

### ISSUE THREAD

**Issue by SchneeHertz** [gaoyb7/115drive-webdav#9]
你好，115 PC客户端获取到的cookie是session级别的，很容易失效。是否有考虑支持直接用115账号登录？

**Comment by gaoyb7** [comment]
直接帐号登录会踢掉其他端的，不建议。可以抓包app的cookie，这个时效很长，我用了快一个月都没掉，只要app不掉，webdav也不会掉

**Comment by gaoyb7** [comment]
> 你好，115 PC客户端获取到的cookie是session级别的，很容易失效。是否有考虑支持直接用115账号登录？

直接帐号登录会踢掉其他端的，不建议。可以抓包app的cookie，这个时效很长，我用了快一个月都没掉，只要app不掉，webdav也不会掉

**Comment by SchneeHertz** [comment]
那问一下用什么工具能抓到app的cookie？

**Comment by gaoyb7** [comment]
> 那问一下用什么工具能抓到app的cookie？

ios 用 stream，android的可以搜下有什么抓包工具
